name: "Websocket flow"

on: push

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

    lint:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Lint
              run: yarn lint

    build:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn build
