name: "Websocket flow"

on: push

jobs:
    install:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node-version: [22.x, 24.x]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: install node-version
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "yarn"
            - name: install depts
              run: yarn install --frozen-lockfile

    lint:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node-version: [22.x, 24.x]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: setup node-version
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
                  cache: "yarn"
            - name: install depts
              run: yarn install --frozen-lockfile
            - name: lint
              run: yarn lint
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
                node-version: [22.x, 24.x]
        runs-on: ${{matrix.os}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: setup node-version
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
                  cache: "yarn"
            - name: install depts
              run: yarn install --frozen-lockfile
            - name: run build
              run: yarn build
