name: "Websocket flow"

on: push

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: install depts
              run: yarn install

    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: install depts
              run: yarn install
            - name: lint
              run: yarn lint
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: install depts
              run: yarn install
            - name: run build
              run: yarn build
